pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scmGit(
                    branches: [[name: '*/Project-4.3']],
                    extensions: [],
                    userRemoteConfigs: [[url: 'https://github.com/akhilkumar0024/Terraform_Project_Skillfyme.git']]
                )
            }
        }

        stage('Terraform Initialization') {
            steps {
                dir('Project-4.1') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('Project-4.1') {
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'AWS -ACCESS-KEY']]) {
                        sh 'terraform plan -out tfplan'
                    }
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('Project-4.1') {
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'AWS -ACCESS-KEY']]) {
                        sh 'terraform apply tfplan'
                    }
                }
            }
        }
        stage('Terraform Destroy') {
            input {
                message 'Are you sure you want to destroy the resources?'
                ok 'Submit'
                parameters {
                    choice(name: 'DESTROY_CHOICE', choices: ['yes', 'no'], description: 'Select "yes" to destroy resources or "no" to exit without destroying')
                }
            }
            steps {
                script {
                    if (env.DESTROY_CHOICE == 'yes') {
                        dir('Project-4.1') {
                            withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'AWS -ACCESS-KEY']]) {
                                sh 'terraform destroy -auto-approve'
                            }
                        }
                    } else {
                        echo 'Exiting pipeline without destroying resources.'
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished executing'
        }
        success {
            echo 'Pipeline executed successfully'
        }
        failure {
            echo 'Pipeline failed'
        }
    }
}
