pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scmGit(
                    branches: [[name: '*/Project-4.3']],
                    extensions: [],
                    userRemoteConfigs: [[url: 'https://github.com/akhilkumar0024/Terraform_Project_Skillfyme.git']]
                )
            }
        }

        stage('Terraform Initialization') {
            steps {
                dir('Project-4.1') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('Project-4.1') {
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'AWS -ACCESS-KEY']]) {
                        sh 'terraform plan -out tfplan'
                    }
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('Project-4.1') {
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'AWS -ACCESS-KEY']]) {
                        sh 'terraform apply tfplan'
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished executing'
        }
        success {
            echo 'Pipeline executed successfully'
        }
        failure {
            echo 'Pipeline failed'
        }
    }
}
